language: php

php:
  - 7.2
  - 7.3

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

sudo: false

services:
  - mysql

install:
  - mysql -e 'create database if not exists laravel;'
  - travis_retry composer create-project --prefer-dist laravel/laravel laravel-tests
  - cp -f ./tests/resources/stubs/artisan ./laravel-tests/
  - cp -f ./tests/resources/stubs/ComposerConfigCommand.php ./laravel-tests/app/
  - cd ./laravel-tests
  - php artisan admin:composer-config
  - travis_retry composer require dcat/laravel-admin:*@dev --no-interaction --prefer-dist --dev

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - php artisan dusk